version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - ML_SERVICE_URL=http://ml-service:5001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - ml-service
    
  ml-service:
    build: ./ml-service
    ports:
      - "5001:5001"
    environment:
      - MAIN_BACKEND_URL=http://backend:5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
